[theme]
base = "dark"
primaryColor = "#0EA5E9"
backgroundColor = "#06121d"
secondaryBackgroundColor = "#0a1a2b"
textColor = "#E6F4FF"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
